name: API REST

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Action para comprovar que el repositorio este  disponible
        with:
          fetch-depth: 0 #Recupera la historia completa del repo
      - uses: actions/setup-node@v4 #Action para configurar el node
        with:
          cache: "npm"
          node-version: "20"
      - name: Install dependencies
        run: npm ci
      - name: Execute Eslint
        run: npm run eslint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Action para comprovar que el repositorio este disponible
        with:
          fetch-depth: 0 #Recupera la historia completa del repo
      - uses: actions/setup-node@v4 # Action para configurar el node
        with:
          cache: "npm"
          node-version: "20"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v4 # Action para subir los resultados como (artifacts) generados en el workflow, para poder ser utilizados
        with:
          name: dist # Name of artifact
          path: dist # Path of where to upload artifact

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Action para comprovar que haya un repositorio disponible
        with:
          fetch-depth: 0 # Recupera la historia completa del repo
      - uses: actions/setup-node@v4 #Action para configurar el node
        with:
          cache: "npm"
          node-version: "20"
      - name: Install dependencies
        run: npm ci
      - uses: actions/download-artifact@v4 # Action para descargar datos(artifacts) generados en el workflow anteriormente
        with:
          name: dist # Name of artifact
          path: dist # Path of where to download artifact
      - name: Execute Test
        run: npm test
